# Generated by Django 4.2.2 on 2023-06-26 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('movie', models.FileField(upload_to='movies/')),
                ('desc', models.CharField(max_length=255)),
                ('createdat', models.DateTimeField(default=datetime.datetime.now)),
                ('language', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('quality', models.CharField(max_length=255)),
            ],
        ),
    ]
