# Generated by Django 4.2.2 on 2023-06-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_moviedatabase_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedatabase',
            name='desc',
            field=models.CharField(max_length=955),
        ),
    ]
