# Generated by Django 4.2.2 on 2023-07-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_moviedatabase_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedatabase',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='moviedatabase',
            name='image',
        ),
        migrations.AlterField(
            model_name='moviedatabase',
            name='movie',
            field=models.FileField(upload_to='movie/'),
        ),
    ]
